### test
GET http://localhost:3500/api/health

### reg
POST http://localhost:3500/api/register HTTP/1.1
content-type: application/json

{
    "login": "xxx",
    "password": "yyy",
    "phone": "123",
    "email": "zzz"
}

### confirm registration
GET http://localhost:3500/api/confirm?link=LSXQcb05LA5wORQFhXXfdx0XbPJeql3gQuu2AToIgXQ

### login OK
POST http://localhost:3500/api/login HTTP/1.1
content-type: application/json

{
    "login": "aaa",
    "password": "bbb",
}

### login OK
POST http://localhost:3500/api/login HTTP/1.1
content-type: application/json

{
    "login": "xxx",
    "password": "yyy"
}